#!/bin/bash

exec 2>&1

HOME="{{pkg.svc_var_path}}"

exec circonus-agentd \
  --api-app="circonus-agent" \
  --api-key="{{cfg.api.key}}" \
  --check-broker "{{cfg.check.broker}}" \
  {{#if cfg.check.create ~}}--check-create \{{/if ~}}
  --collectors="{{cfg.collectors}}" \
  {{#if cfg.check.enable_new_metrics ~}}--check-enable-new-metrics \{{/if ~}}
  --check-metric-state-dir="{{pkg.svc_var_path}}"\
  --check-target="{{sys.ip}}" \
  --check-title="Circonus Agent on {{sys.hostname}}" \
  --listen="127.0.0.1:2609" \
  {{#if cfg.log.pretty ~}}--log-pretty \{{/if ~}}
  {{#if cfg.statsd.disabled ~}}--no-statsd \{{/if ~}}
  --plugin-dir="{{pkg.path}}/plugins" {{#if cfg.reverse ~}}--reverse{{/if ~}}
