#!/bin/bash

exec 2>&1

HOME="{{pkg.svc_var_path}}"

{{#each cfg.plugin_packages as |package| ~}}
  PATH="$PATH:$(hab pkg path {{package}})"
{{/each}}

if [ "$(whoami)" = "root" ]
then
  exec chpst -U hab -u hab circonus-agentd --config {{pkg.svc_config_path}}/agent.json
else
  exec circonus-agentd --config {{pkg.svc_config_path}}/agent.json
fi
